# Generated by Django 2.2.4 on 2021-03-03 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='upvote_total',
            field=models.IntegerField(null=True),
        ),
    ]
