# Generated by Django 2.2.4 on 2021-03-04 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_app', '0002_auto_20210303_0536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=20)),
                ('search', models.CharField(max_length=45)),
                ('meal', models.CharField(choices=[('D', 'Dinner'), ('L', 'Lunch'), ('B', 'Breakfast'), ('S', 'Snack'), ('De', 'Dessert')], default='D', max_length=2)),
                ('upvoted_total', models.IntegerField(default=0)),
                ('upvoted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_upvote', to='kitchen_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.TextField()),
                ('yummy', models.IntegerField()),
                ('upvoted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_upvote', to='kitchen_app.User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_by_user', to='kitchen_app.User')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_of_video', to='kitchen_app.Video')),
            ],
        ),
    ]
