# Generated by Django 2.2.4 on 2021-03-04 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_app', '0006_auto_20210304_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='meal',
            field=models.CharField(blank=True, choices=[('D', 'Dinner'), ('L', 'Lunch'), ('B', 'Breakfast'), ('S', 'Snack'), ('De', 'Dessert')], default='D', max_length=2, null=True),
        ),
    ]
