# Generated by Django 2.2.4 on 2021-03-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_app', '0008_auto_20210304_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='easy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='entertaining',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='good',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='healthy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='yummy',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
